/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDireccionIP = new javax.swing.JLabel();
        ip1 = new javax.swing.JTextField();
        ip2 = new javax.swing.JTextField();
        ip3 = new javax.swing.JTextField();
        ip4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTituloClase = new javax.swing.JLabel();
        buttonGenerar = new javax.swing.JButton();
        labelClase = new javax.swing.JLabel();
        labelTituloDireccionRed = new javax.swing.JLabel();
        labelTituloDireccionBroadcast = new javax.swing.JLabel();
        labelTituloMascara = new javax.swing.JLabel();
        labelMascara = new javax.swing.JLabel();
        labelDireccionRed = new javax.swing.JLabel();
        labelDireccionBroadcast = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        labelMascara2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDireccionIP.setText("Introduce una dirección IP:");

        ip1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip1KeyTyped(evt);
            }
        });

        ip2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip2KeyTyped(evt);
            }
        });

        ip3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip3KeyTyped(evt);
            }
        });

        ip4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip4KeyTyped(evt);
            }
        });

        jLabel1.setText(".");

        jLabel2.setText(".");

        jLabel3.setText(".");

        labelTituloClase.setText("Clase:");

        buttonGenerar.setText("Generar");
        buttonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarActionPerformed(evt);
            }
        });

        labelClase.setText("-");

        labelTituloDireccionRed.setText("Dirección de red:");

        labelTituloDireccionBroadcast.setText("Dirección de broadcast:");

        labelTituloMascara.setText("Máscara:");

        labelMascara.setText("-");

        labelDireccionRed.setText("-");

        labelDireccionBroadcast.setText("-");

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ip.jpg"))); // NOI18N

        labelMascara2.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonGenerar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTituloDireccionRed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelDireccionRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTituloClase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelClase, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTituloMascara)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMascara2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icono))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTituloDireccionBroadcast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDireccionBroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDireccionIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ip2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ip3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionIP)
                    .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ip4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(ip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonGenerar)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTituloClase)
                            .addComponent(labelClase)
                            .addComponent(labelTituloMascara)
                            .addComponent(labelMascara))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMascara2)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTituloDireccionRed)
                            .addComponent(labelDireccionRed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTituloDireccionBroadcast)
                            .addComponent(labelDireccionBroadcast))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(icono)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ip1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip1KeyTyped
    // TODO add your handling code here:
    int limite=3;
    char caracter=evt.getKeyChar();
    if(ip1.getText().length()==limite||Character.isLetter(caracter)){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_ip1KeyTyped

    private void ip2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip2KeyTyped
        // TODO add your handling code here:
        int limite=3;
    char caracter=evt.getKeyChar();
    if(ip2.getText().length()==limite||Character.isLetter(caracter)){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_ip2KeyTyped

    private void ip3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip3KeyTyped
        // TODO add your handling code here:
        int limite=3;
    char caracter=evt.getKeyChar();
    if(ip3.getText().length()==limite||Character.isLetter(caracter)){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_ip3KeyTyped

    private void ip4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip4KeyTyped
        // TODO add your handling code here:
        int limite=3;
    char caracter=evt.getKeyChar();
    if(ip4.getText().length()==limite||Character.isLetter(caracter)){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_ip4KeyTyped

    private void buttonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarActionPerformed
        if(ip1.getText().isEmpty() || ip2.getText().isEmpty() || ip3.getText().isEmpty() || ip4.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Introduce un direccion IPv4 valida");
        }else{
            int ipSeccion1 = Integer.parseInt(ip1.getText());
            int ipSeccion2 = Integer.parseInt(ip2.getText());
            int ipSeccion3 = Integer.parseInt(ip3.getText());
            int ipSeccion4 = Integer.parseInt(ip4.getText());
            if(ipSeccion2 < 256 && ipSeccion3 <256 && ipSeccion4 < 256){
                if(ipSeccion1 < 128){
                    labelClase.setText("A");
                    labelMascara.setText("255.0.0.0");
                    labelMascara2.setText("/8");
                    labelDireccionRed.setText(ipSeccion1+"."+"0.0.0");
                    labelDireccionBroadcast.setText(ipSeccion1+"."+"255.255.255");
                }else if(ipSeccion1 < 192){
                    labelClase.setText("B");
                    labelMascara.setText("255.255.0.0");
                    labelMascara2.setText("/16");
                    labelDireccionRed.setText(ipSeccion1+"."+ipSeccion2+"."+"0.0");
                    labelDireccionBroadcast.setText(ipSeccion1+"."+ipSeccion2+"."+"255.255");
                }else if(ipSeccion1 < 224){
                    labelClase.setText("C");
                    labelMascara.setText("255.255.255.0");
                    labelMascara2.setText("/24");
                    labelDireccionRed.setText(ipSeccion1+"."+ipSeccion2+"."+ipSeccion3+"."+"0");
                    labelDireccionBroadcast.setText(ipSeccion1+"."+ipSeccion2+"."+ipSeccion3+"."+"255");
                }else{
                    JOptionPane.showMessageDialog(null, "Introduce un direccion IPv4 valida (Clase A,B o C)");
                }// TODO add your handling code here:
            }else{
                JOptionPane.showMessageDialog(null, "Introduce un direccion IPv4 valida");
            }
        }
    }//GEN-LAST:event_buttonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGenerar;
    private javax.swing.JLabel icono;
    private javax.swing.JTextField ip1;
    private javax.swing.JTextField ip2;
    private javax.swing.JTextField ip3;
    private javax.swing.JTextField ip4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelClase;
    private javax.swing.JLabel labelDireccionBroadcast;
    private javax.swing.JLabel labelDireccionIP;
    private javax.swing.JLabel labelDireccionRed;
    private javax.swing.JLabel labelMascara;
    private javax.swing.JLabel labelMascara2;
    private javax.swing.JLabel labelTituloClase;
    private javax.swing.JLabel labelTituloDireccionBroadcast;
    private javax.swing.JLabel labelTituloDireccionRed;
    private javax.swing.JLabel labelTituloMascara;
    // End of variables declaration//GEN-END:variables
}
